### PR TITLE
Organization list can be filtered

### PR DESCRIPTION
**Pull request by Matoking**
- Organization list can now be filtered.
- Slight styling changes.

### CODE REVIEW

**Comment by TwilightCode** [comment]
Suffers currently of some scaling issues when browser is stretched horizontally or viewed on a laptop (fullscreen). Issue is that all organizations listed, end up outside the screen (Only checkbox is visible on the right side. Search bar is also moved).

**Comment by Matoking** [comment]
I couldn't reproduce that issue. Could you upload a screenshot of the bug? What browser are you using?

**Comment by TwilightCode** [comment]
Browser is firefox  v 41.0.2
Tested also on a chromium browser and issue didn't appear. 
Laptop is Lenovo T400, screen size '14,1' inch

Here's a picture when I'm fullscreen and scaling breaks:

screenshot from 2016-08-31 20-02-01

Here's a picture when issue first occurs:

screenshot from 2016-08-31 20-03-56

Here's a picture when everything is working accordingly:

screenshot from 2016-08-31 20-03-43

Any browser size smaller than the picture is fine. Opposite is also true.

**Comment by TwilightCode** [comment]
I did some extra digging on the issue and by disabling certain styles could get following results:

screenshot from 2016-08-31 22-07-33

Following picture shows the styles that seem to be the culprits:

screenshot from 2016-08-31 22-09-25

Mostly float:left and margin-left: 75% seem to cause the issue when width of the browser gets high enough.

**Comment by TwilightCode** [comment]
Here are the styles in a close up:

Only margin-left: 75% disabled:

screenshot from 2016-08-31 22-30-55

Only float: left; disabled:

screenshot from 2016-08-31 22-30-33

**Comment by TwilightCode** [comment]
Issue has now been resolved.

**Pull request merged**
