### PR TITLE
Added FAQ to navbar. FAQ items are expanded/shown by default.

### PR DESCRIPTION
**Pull request by kkirjala**

### CODE REVIEW

**Comment by Matoking** [comment]
- The FAQ page doesn't fill the entire horizontal grid for some reason (eg. <div class="col-md-8"> is used instead of <div class="col-md-12"> in faq/faq.html).

**Comment by kkirjala** [comment]
Fixed.

**Comment by TwilightCode** [comment]
Looks pretty good. I was wondering should the panel-heading and -body have different colors in this version to separate them from each other and from other panels. 
There is a feature in this version that should you click any panel-heading and then reclick it, all other panels are closed and only one is opened (Not sure if a feature or a bug).

**Comment by kkirjala** [comment]
Now the heading (panel-title) of a FAQ item is uniform with the rest of the site.

Obviously my status bar (process step indicator) is now part of this pull request too as I accidentally did it in the same branch.

**Pull request merged**
